"""update db

Revision ID: 231ea22500d3
Revises: 
Create Date: 2025-10-05 14:20:17.592671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231ea22500d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=True),
    sa.Column('receiver_email', sa.String(length=50), nullable=True),
    sa.Column('order_code', sa.String(length=50), nullable=True),
    sa.Column('mail_content', sa.String(length=2000), nullable=True),
    sa.Column('receiver_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_plan', sa.String(length=500), nullable=True),
    sa.Column('store_name', sa.String(length=50), nullable=True),
    sa.Column('receive_dead_line', sa.DateTime(), nullable=True),
    sa.Column('delivery_company', sa.String(length=50), nullable=True),
    sa.Column('delivery_tracking_code', sa.String(length=50), nullable=True),
    sa.Column('delivery_tracking_link', sa.String(length=500), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('order_detail')
    # ### end Alembic commands ###
