"""add color and sizes

Revision ID: 28e8f4383d26
Revises: 95359ce3a856
Create Date: 2025-10-27 22:54:35.412690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e8f4383d26'
down_revision = '95359ce3a856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_order_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('export_flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_order_info')
    # ### end Alembic commands ###
