"""add color and sizes

Revision ID: 95359ce3a856
Revises: d77c49f8254a
Create Date: 2025-10-26 23:38:11.369966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95359ce3a856'
down_revision = 'd77c49f8254a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=255), nullable=True),
    sa.Column('color_code', sa.String(length=255), nullable=True),
    sa.Column('imageLink', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_size',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('size_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['product_color.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_size')
    op.drop_table('product_color')
    # ### end Alembic commands ###
