"""add category

Revision ID: f828c21b91c5
Revises: 
Create Date: 2025-09-24 22:16:31.245343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f828c21b91c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('discountFlg', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('imageLink', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
